Ambient Meta Update
logdna/nodejs pull request #66
Opened 2019-08-15 21:00 UTC by smusali

Updated:
- The implementation of `Ambient Meta`
- Appropriate Unit Tests
- [`README.md`](https://github.com/logdna/nodejs/blob/ambientMetaUpdate/README.md)

2019-08-19 20:18 UTC, andkon requested changes
Just a small formatting change to make it consistent with the README. Otherwise LGTM!

2019-08-19 20:18 UTC, andkon commented on README.md
> +A function that adds `key`/`value` pair into the `line`.
I'd remove the escaped `line` and just put "line," as that's how it appears throughout the README currently.

2019-08-19 20:18 UTC, andkon commented on README.md
> +A function that removes the `key` and associated `value` from the `line`.
Same, s/`line`/line/h

2019-08-19 21:50 UTC, smusali commented on README.md
> +A function that removes the `key` and associated `value` from the `line`.
Ooops...

2019-08-19 21:52 UTC, smusali commented
@andkon, updated! Can you take a look @ the changes again for the second time? Thanks in advance!

2019-08-20 00:00 UTC, dchai76 commented on lib/logger.js
> +            if (opts.timestamp && isValidTimestamp(opts.timestamp)) { message.timestamp = opts.timestamp; }
This is a style thing, but I prefer having bracketed statements in their own line. In other words, like it was before your change. More readable and better for git blame/history.

2019-08-20 00:00 UTC, dchai76 commented on lib/logger.js
> +                } else { message.meta = stringify(opts.meta); }
Same as above, this is less readable than if both `if`/`else` clauses are indented similarly.

2019-08-20 00:00 UTC, dchai76 commented on lib/logger.js
> +    this._meta_keys += 1;
This type of coordination is error-prone. Why not just check for the count of keys in `this._meta` directly instead of tracking it in parallel with `_meta_keys`?

As a side note (since I recommend you remove it altogether) this is JS, not Python - I think `_meta_keys++` is the preferred style.

2019-08-20 00:00 UTC, dchai76 commented on lib/logger.js
> +    }
Is it worth erroring (or logging) if they try to remove a key that does not exist?

2019-08-20 00:00 UTC, dchai76 commented on test/testHelper.js
> +module.exports.stringifiedObjectsEqual = function(a, b) {
It seems there are built-ins you can use instead of this. Maybe `jsonEqual` (https://www.chaijs.com/plugins/chai-json-equal/) or `JSON.parse` within each test and use the standard `assert.deepEqual`. I'd prefer we use one of those.

2019-08-20 00:00 UTC, dchai76 commented on test/logger.js
> +        assert(ambientLogger._buf[1].meta === undefined);
This goes for all over the test file but I'm much more accustomed to seeing `assert.equal(`... than `assert(x === y)` in unit tests.

2019-08-20 17:27 UTC, smusali commented
@dchai76 @andkon can you do the final round review? Thanks in advance!

2019-08-20 17:29 UTC, dchai76 approved these changes

2019-08-20 18:37 UTC, merged